DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL
);

CREATE TABLE post (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	author_id INTEGER NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	o_mithril INTEGER NOT NULL,
	o_oric INTEGER NOT NULL,
	w_elder INTEGER NOT NULL,
	w_ancient INTEGER NOT NULL,
	l_rough INTEGER NOT NULL,
	l_hardened INTEGER NOT NULL,
	c_silk INTEGER NOT NULL,
	c_gossamer INTEGER NOT NULL,
	lucentmotes INTEGER NOT NULL,
	reclaimedmetal INTEGER NOT NULL,
	s_pain INTEGER NOT NULL,
	s_enhance INTEGER NOT NULL,
	s_control INTEGER NOT NULL,
	c_skill INTEGER NOT NULL,
	c_potency INTEGER NOT NULL,
	c_brilliance INTEGER NOT NULL,
	luck10 INTEGER NOT NULL,
	luck50 INTEGER NOT NULL,
	luck100 INTEGER NOT NULL,
	luck200 INTEGER NOT NULL,
	rare INTEGER NOT NULL,
	exotic INTEGER NOT NULL,
	r_salvaged INTEGER NOT NULL,
	e_salvaged INTEGER NOT NULL,
	r_ecto INTEGER NOT NULL,
	e_ecto INTEGER NOT NULL,
	FOREIGN KEY (author_id) REFERENCES user (id)
);